name: Gradle Build

on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Gradle Build
        run: ./gradlew build --no-daemon

  release:
    needs: build
    if: github.ref == 'refs/heads/master' && contains(github.event.head_commit.message, '[release]')
    uses: ./.github/workflows/release.yml
    secrets: inherit
