on:
  workflow_dispatch:

#  push:
#    branches: [ add_release_automation ]
#    paths: [ VERSION ]

jobs:
  release:
    if: "contains(github.event.head_commit.message, '[release]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Publish Plugin
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: ./gradlew publishPlugins --no-daemon --stacktrace